# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b1cef0c8a0ec4cb2128d7d786d7565bf7434a0a09b067bc57c8dbc1ed0f1d1b730808f0cc19596f49acba919fdd97bf76ab3037c02ed23b3ec28d32433e5d6e

test:
  secret_key_base: a95e1e9d96a207e9ec70b00a2edf3db1bab6db11e6afe7c7cfa77f2bfc2e55a52ee9e104dc04368d6797d2c250c7bdaf25e055fee74356147d9a258b4c4725d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
